name: Windows RDP via Telebit

on: workflow_dispatch

jobs:
  rdp-tunnel:
    runs-on: windows-latest
    steps:
    - name: Setup Node.js 10.2.1
      uses: actions/setup-node@v3
      with:
        node-version: 10.2.1

    - name: Install Telebit globally
      run: npm install -g telebit

    - name: Create Telebit config file with email and TOS acceptance
      shell: pwsh
      run: |
        mkdir "$env:USERPROFILE\.config\telebit" -ErrorAction Ignore
        @"
email: "nerysvan34@gmail.com"
agree_tos: true
"@ | Out-File -Encoding utf8 "$env:USERPROFILE\.config\telebit\telebitd.yml"

    - name: Start Telebit daemon forwarding TCP 3389
      shell: pwsh
      run: Start-Process -NoNewWindow -FilePath telebit -ArgumentList 'tcp 3389' -PassThru

    - name: Show Telebit tunnels and keep alive
      shell: pwsh
      run: |
        Start-Sleep -Seconds 10
        telebit list
        Start-Sleep -Seconds 3600
