name: PC

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Baixar Telebit
      run: Invoke-WebRequest https://telebit.cloud/telebit.exe -OutFile telebit.exe

    - name: Preparar Telebit (Primeira Execução)
      run: |
        echo y | .\telebit.exe autoconfigure --accept-defaults --email nerysvan34@gmail.com

    - name: Habilitar Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Definir Senha do Usuário
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Criar túnel RDP com Telebit
      run: .\telebit.exe tcp 3389
